
name: Integration # name of the workflow or what yaml file denotes

on: # on which event this job should trigger
  push: #push happen to main branch
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: # has multiple jobs
  build:

    runs-on: ubuntu-latest # which OS to run the job on run on github servers

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Installing Dependencies"
      run: npm i

    - name: "Build command"
      run: npm run build

  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4 # checkout to the current branch default is main branch
    - name: Use Node.js ${{ matrix.node-version }} # use the node version from matrix completely optional
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} # told in strategy
        cache: 'npm'
    - name: "Installing Dependencies"
      run: npm i
    - name: "Running test cases"
      run: npm run test
    